name: blcxh5

services:
  mysql:
    image: docker.io/library/mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Your custom my.cnf mounted inside container
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro

  blcxh5-backend:
    image: blcxh5-backend
    container_name: blcxh5-backend
    restart: always
    ports:
      - "9503:9503"   # backend port
      - "9506:9506"   # admin port
    depends_on:
      - mysql

volumes:
  mysql_data:
