# blcxh5-mysql.container
[Container]
ContainerName=mysql
Environment=MYSQL_ROOT_PASSWORD=123456
Image=docker.io/library/mysql:8.0
Pod=blcxh5.pod
Volume=mysql_data:/var/lib/mysql
Volume=./my.cnf:/etc/mysql/conf.d/my.cnf:Z

[Service]
Restart=always

---

# blcxh5-blcxh5-backend.container
[Unit]
Requires=mysql.service
After=mysql.service

[Container]
ContainerName=blcxh5-backend
Image=blcxh5-backend
Pod=blcxh5.pod

[Service]
Restart=always

---

# blcxh5.pod
[Pod]
PublishPort=127.0.0.1:3306:3306
PublishPort=127.0.0.1:9503:9503
PublishPort=127.0.0.1:9506:9506
