# tkvdh5-mongodb.container
[Container]
ContainerName=mongodb
Image=mongo:6.0.10
Pod=tkvdh5.pod
Volume=mongo_data:/data/db

[Service]
Restart=always

---

# tkvdh5-redis.container
[Container]
ContainerName=redis
Exec=redis-server --appendonly yes
Image=redis:7.2
Pod=tkvdh5.pod
Volume=redis_data:/data

[Service]
Restart=always

---

# tkvdh5-backend.container
[Unit]
Requires=mongodb.service redis.service
After=mongodb.service redis.service

[Container]
ContainerName=tkvdh5-backend
Image=tkvdh5-backend
Pod=tkvdh5.pod

[Service]
Restart=always

---

# tkvdh5.pod
[Pod]
PublishPort=27017:27017
PublishPort=6379:6379
PublishPort=3030:3030
PublishPort=4030:4030
